### PR TITLE
1.6.0

### PR DESCRIPTION
**Pull request by gtache**
-Update to lsp4j 0.8.1    
-Update to flexmark 0.42.12    
-Adds restart server option when clicking on the status icon    
-Adds (wonky) snippet completion support    
-Adds initialized support    
-Adds configuration and didChangeConfiguration support    
-Adds dynamic DidChangeWatchedFiles registration to filter file events    
-Adds standard LanguageID    
-Diagnostics are now shown when reported range length is 0    
-Fixes modifying server definitions for existing extensions    
-Fixes incremental synchronization on didChange    
-Fixes document highlights    
-Fixes offsets with tabs having different sizes    
-Fixes offsets while doing multiple edits

### CODE REVIEW

**Comment by andre2007** [comment]
@gtache as the last commit is some weeks ago the question, is this plugin still maintained or did you stopped the work?

**Comment by gtache** [comment]
Alright, this release is more or less ready, only problem is that my JetBrains account is not "remembering" that I am the author of this plugin (meaning I can't update it).     
I'll contact them to fix that, so as soon as it's done I'll update the plugin.

**Comment by andre2007** [comment]
@gtache I already pulled your changes. In the plugin settings dialog on item "Language Server Protocol" there is an endless loading indicator:

image

**Comment by gtache** [comment]
@andre2007 That's strange, I can't reproduce this behavior. Which IDE and version are you using ? Do you see anything in the log ?

**Comment by andre2007** [comment]
I use most  recent IDEA, the logs I can have a look when  I have access to my work station again.

**Comment by andre2007** [comment]
I don't know whether this is related, but I also get this error for the "1.6.0" branch:

> cannot create configurable component
> 
> com.intellij.diagnostic.PluginException: While loading class com.github.gtache.lsp.settings.gui.MiscGUI: Duplicate method name "$$$getFont$$$" with signature "(Ljava.lang.String;IILjava.awt.Font;)Ljava.awt.Font;" in class file com/github/gtache/lsp/settings/gui/MiscGUI [Plugin: com.github.gtache.lsp]
> 	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:221)
> 	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:165)
> 	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:73)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
> 	at com.github.gtache.lsp.settings.MiscSettings.createComponent(MiscSettings.java:41)
> 	at com.intellij.openapi.options.ex.ConfigurableWrapper.createComponent(ConfigurableWrapper.java:155)
> 	at com.intellij.openapi.options.ex.ConfigurableCardPanel.lambda$createConfigurableComponent$0(ConfigurableCardPanel.java:74)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:932)
> 	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
> 	at com.intellij.openapi.options.ex.ConfigurableCardPanel.createConfigurableComponent(ConfigurableCardPanel.java:70)
> 	at com.intellij.openapi.options.ex.ConfigurableCardPanel.create(ConfigurableCardPanel.java:56)
> 	at com.intellij.openapi.options.newEditor.ConfigurableEditor$1.create(ConfigurableEditor.java:56)
> 	at com.intellij.openapi.options.newEditor.ConfigurableEditor$1.create(ConfigurableEditor.java:53)
> 	at com.intellij.ui.CardLayoutPanel.createValue(CardLayoutPanel.java:87)
> 	at com.intellij.ui.CardLayoutPanel.select(CardLayoutPanel.java:115)
> 	at com.intellij.ui.CardLayoutPanel.lambda$null$0(CardLayoutPanel.java:131)
> 	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:312)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:433)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
> 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
> 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:824)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:773)
> 	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:412)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:693)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:411)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
> 	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
> 	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
> 	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
> 	at java.desktop/java.awt.Dialog.show(Dialog.java:1063)
> 	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:707)
> 	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:432)
> 	at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1685)
> 	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1644)
> 	at com.intellij.openapi.options.newEditor.SettingsDialog.lambda$show$0(SettingsDialog.java:77)
> 	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:82)
> 	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:148)
> 	at com.intellij.openapi.options.newEditor.SettingsDialog.show(SettingsDialog.java:77)
> 	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:84)
> 	at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:54)
> 	at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:41)
> 	at com.intellij.openapi.wm.impl.welcomeScreen.FlatWelcomeFrame$FlatWelcomeScreen$IconsFreeActionGroup$1.actionPerformed(FlatWelcomeFrame.java:813)
> 	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:265)
> 	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
> 	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:256)
> 	at com.intellij.ui.popup.ActionPopupStep.performAction(ActionPopupStep.java:200)
> 	at com.intellij.ui.popup.ActionPopupStep.performAction(ActionPopupStep.java:190)
> 	at com.intellij.ui.popup.ActionPopupStep.lambda$onChosen$2(ActionPopupStep.java:184)
> 	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:192)
> 	at com.intellij.ui.popup.AbstractPopup.lambda$dispose$13(AbstractPopup.java:1428)
> 	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2464)
> 	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:168)
> 	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:120)
> 	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:161)
> 	at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1424)
> 	at com.intellij.ui.popup.WizardPopup.dispose(WizardPopup.java:162)
> 	at com.intellij.ui.popup.list.ListPopupImpl.dispose(ListPopupImpl.java:318)
> 	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.dispose(PopupFactoryImpl.java:278)
> 	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:47)
> 	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:43)
> 	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:135)
> 	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:104)
> 	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:194)
> 	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:104)
> 	at com.intellij.openapi.util.objectTree.ObjectTree.executeAll(ObjectTree.java:142)
> 	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:136)
> 	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:132)
> 	at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:263)
> 	at com.intellij.ui.popup.list.ListPopupImpl.handleNextStep(ListPopupImpl.java:453)
> 	at com.intellij.ui.popup.list.ListPopupImpl._handleSelect(ListPopupImpl.java:407)
> 	at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:353)
> 	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.handleSelect(PopupFactoryImpl.java:298)
> 	at com.intellij.ui.popup.list.ListPopupImpl$MyMouseListener.mouseReleased(ListPopupImpl.java:512)
> 	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
> 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
> 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
> 	at com.intellij.ui.popup.list.ListPopupImpl$MyList.processMouseEvent(ListPopupImpl.java:566)
> 	at java.desktop/java.awt.Component.processEvent(Component.java:6416)
> 	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
> 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
> 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
> 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
> 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
> 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
> 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:824)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:769)
> 	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:412)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:411)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
> Caused by: java.lang.ClassFormatError: Duplicate method name "$$$getFont$$$" with signature "(Ljava.lang.String;IILjava.awt.Font;)Ljava.awt.Font;" in class file com/github/gtache/lsp/settings/gui/MiscGUI
> 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
> 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:877)
> 	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:335)
> 	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:330)
> 	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:294)
> 	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:218)
> 	... 120 more

**Comment by gtache** [comment]
That's a strange one, the only reasons I can think of are either the runtime version (you are using Java 11, I'm still on 8) or there is still some code left from the previous plugin installation (maybe try deleting the plugin in IntelliJ as well as manually to be sure, clear caches and reinstall it?)

**Comment by andre2007** [comment]
I tried to exclude this possibility by doing a new git clone, building everything from scratch. 
I now also tried it in PyCharme and have the same issue here.

**Comment by andre2007** [comment]
@gtache I think I found an even bigger issue. In combination with DLS (https://github.com/d-language-server/dls) IntelliJ freezes every time you just save a file. This doesn't happen with the current version of LSP. I do not know whether this is an issue with DLS or with the upcoming 1.6.0 changes.

**Comment by gtache** [comment]
Sorry for the delay, I'm in a pretty busy period but starting from next week it should be better.    
Sadly I can't seem to reproduce your issue, I tried the DLS with IntelliJ, and get no freeze at all. Do you get anything in the log when it happens?

**Pull request merged**
