### PR TITLE
[#38] fixed potential IndexOutOfBoundsException

### PR DESCRIPTION
**Pull request by cdietrich**

### CODE REVIEW

**Comment by gtache** [comment]
Thanks for the PR!

It seems to me that it is more like a bandaid than a fix, because ideally pos.getCharacter shouldn't be greater than the line length anyway (or perhaps if the server sends incorrect information).     
I'll just need some time to get back into the project and check if it makes sense to add this (although it shouldn't hurt)

**Comment by gtache** [comment]
Well, it won't cause problem anyway, I'll just add a log to keep track of the outofbounds. Thanks!

**Comment by Christoph-Majcen** [comment]
I had already problems, when you delete a lot of characters at once, if the server does not keep up, it can cause issues. Also it mentions in the official spec for position ( https://microsoft.github.io/language-server-protocol/specification#position ) that "If the character value is greater than the line length it defaults back to the line length."

**Comment by gtache** [comment]
@Christoph-Majcen Oh I'd missed that, thanks for the info!

**Pull request merged**
